[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on = "<C-y>"
run = "plugin system-clipboard"
desc = "Copy to clipboard"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "shell 'cb paste' --block"
desc = "Paste from clipboard"

[[mgr.prepend_keymap]]
on = ["g", "v"]
run = "cd /Volumes/Phantoms/"
desc = "Go /Volumes/Phantoms/"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = "tab_create --current"
desc = "Open new tab"

[[mgr.prepend_keymap]]
on = ["<Space>", "b", "h"]
run = "tab_switch --relative -1"
desc = "Switch to tab on the left"

[[mgr.prepend_keymap]]
on = ["<Space>", "b", "l"]
run = "tab_switch --relative 1"
desc = "Switch to tab on the right"

[[mgr.prepend_keymap]]
on = ["<Space>", "b", "d"]
run = "close"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on = "o"
run = "shell 'open %s' --block"
desc = "Open with system `open`"
