set -g extended-keys on

set-option -g default-command "reattach-to-user-namespace -l fish"

set -g base-index 1
set -g display-panes-time 2000
set -g renumber-windows on
set -g mode-keys vi
set -g status-keys vi

set -g status-style bg=#373737

# For available variables, see here:
# https://man.openbsd.org/tmux#Variable
set -g status-left-length 100
set -g status-left '#[fg=black,bg=#c7642a] session: #{session_name} #[fg=#c7642a,bg=#ce9c3e] '

set -g status-right '#[fg=#749c6f,bg=#373737]#[fg=#eeeeee,bg=#749c6f] Keep on keeping on! 💪'

set -g window-status-separator ''

# Do not forget the "#" before the comma inside the conditional syntax
# Only show the window index if there is more than one window
set -g window-status-current-format '#[fg=#dddddd,bg=#ce9c3e]#{?#{&&:#{window_start_flag},#{window_end_flag}},,#[fg=#915574#,bold#,underscore]#I. }#W#[nobold,nounderscore,fg=#dddddd] #{?window_end_flag,#[fg=#ce9c3e#,bg=#373737] , }'

# We need only to apply the conditional syntax for the window-status-current-
# format because when there is only one window, it is bound to be the focused
# window.
# Generally, window-status-current-format takes precedence over window-status-
# format. Thus, when there is only one window, window-status-format is of no
# use, meaning that this attribute only takes effect when there is more than one
# window. Therefore, we need not check if there is only one window in window-
# status-format.
set -g window-status-format '#[fg=#dddddd,bg=#ce9c3e]#I. #W #{?window_end_flag,#[fg=#ce9c3e#,bg=#373737] , }'

set -g prefix C-x

unbind C-b
unbind M-1
unbind M-2
unbind M-3
unbind M-4
unbind M-5
unbind M-6
unbind M-7
unbind Up
unbind Down
unbind Left
unbind Right
unbind [
unbind ]
unbind \"
unbind \%
unbind c

bind C-c confirm-before -p "Detach from client? (y/n)" detach-client
bind C-x send-prefix
bind F5 source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind c copy-mode
bind d confirm-before -p "kill-window #W? (y/n)" kill-window
bind n new-window
bind s split-window
bind v split-window -h

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

bind -T root C-q kill-pane
bind -T root C-v run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
