# Press <Ctrl> + <Shift> + <F5> to reload configuration
# Use `kitty +list-fonts` for all available fonts
font_family      JetBrains Mono Regular
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 16.0

disable_ligatures never
modify_font cell_height 110%

cursor_stop_blinking_after 0.0

scrollback_lines 10000

# Hide mouse cursor immediately when typing
mouse_hide_wait -1

url_style straight

visual_bell_duration 1.0

remember_window_size  no
initial_window_width  160c
initial_window_height 36c
window_padding_width 0 0

tab_bar_edge bottom
tab_bar_style powerline
tab_title_max_length 10
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}"

active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal

foreground #dddddd
background #000000
background_opacity 0.8

selection_foreground #000000
selection_background #fffacd

close_on_child_death yes

update_check_interval 0

macos_option_as_alt yes

allow_remote_control yes

mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link

enabled_layouts Splits
window_border_width 4px
draw_minimal_borders false
window_margin_width 5 2
single_window_margin_width 0
active_border_color #dd37dd
inactive_text_alpha 0.7
hide_window_decorations yes

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

map ctrl+alt+n new_tab
map ctrl+q close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

map ctrl+alt+s launch --location=hsplit
map ctrl+alt+v launch --location=vsplit
map ctrl+alt+o layout_action rotate

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down
